image: node:6
clone:
  depth: full
pipelines:
  default:
    - step:
        name: Deploy to Heroku
        deployment: test   # set to test, staging or production
        script:
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
