---
- hosts: Server1
  remote_user: admin
  gather_facts: no
 # sudo: yes
  vars:
    known_hosts_file: "~/.ssh/known_hosts"

  tasks:
 # - name: restore public key
 #   command: echo '"{{ ssh_public_key }}"' > ~/.ssh/id_rsa.pub
 #   register: restorepublickey
 # - debug:
 #     var: restorepublickey.stdout.split('\n')
 # - include: Tasks/update-server.yml
#  - include: Tasks/installation.yml
#   - include: Tasks/secure-mysql.yml
  - include: Tasks/gitcloneproject.yml
  - include: Tasks/apache-firewall-allow.yml

#  - name: Restart Apache
#    command: systemctl restart httpd
  - include: Tasks/install_vsftpd.yml
  - include: Tasks/copy_envfile.yml
  - include: Tasks/install_phpmyadmin.yml

  - name: restore public key
    command: "{{ item }}"
    with_items:
        - systemctl enable httpd
        - systemctl enable mariadb
    register: serviceenable
  - debug:
      var: serviceenable.stdout.split('\n')