- name: install git
  command: yum install git -y
  register: installgit
- debug:
    var: installgit.stdout.split('\n')

#install httpd service (apache 2.4)
- name: install the latest version of Apache
  yum:
    name: httpd
    state: latest
  register: installapache
- debug:
    var: installapache.stdout.split('\n')

#- name: upload config file
#  copy:
#      src: ../../server-config-file/koolpon.conf
#      dest: /etc/httpd/conf.d/koolpon.conf
#  register: copyconfig
#- debug:
#    var: copyconfig.stdout

- name: upload koolpon configruation file
  template: src=../../server-config-file/koolpon.conf dest=/etc/httpd/conf.d/koolpon.conf
  register: copyconfig
- debug:
    var: copyconfig.stdout

#install mysql
- name: Install MySQL
  action: yum name={{ item }}
  with_items:
    - mariadb-server
    - mariadb
  register: installmariadb
- debug:
    var: installmariadb.stdout.split('\n')

- name: Start the MySQL service
  action: service name=mariadb state=started
  register: mariadbstart
- debug:
    var: mariadbstart.stdout.split('\n')

#install php 7
- name: Install PHP 7
  command: "{{ item }}"
  ignore_errors: yes
  with_items:
    - rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
    - yum install php70w php70w-opcache php70w-mysql -y
  register: installphp
- debug:
    var: installphp.stdout.split('\n')

#install composer
- name: Install Composer
  ignore_errors: yes
  action: yum name={{ item }}
  with_items:
    - composer
  register: installcomposer
- debug:
    var: installcomposer.stdout.split('\n')
