- name: restart service
  action: systemctl restart {{ item }}
  with_items:
    - mariadb
    - httpd
    - vsftpd
  register: enablerestartservice
- debug:
    var: enablerestartservice.stdout.split('\n')